In [63]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from ast import literal_eval
from collections import Counter
pd.set_option('display.max_columns', None)
import ast

In [21]:
from PIL import Image
from urllib.request import urlopen

In [22]:
import ssl
import urllib.request

In [23]:
df = pd.read_csv('../data/movies_DB.csv')

In [24]:
df.sample(4)

,movie_id,title,overview,genres,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast
11680,5857,I Know Who Killed Me,An idyllic small town is rocked when Aubrey Fl...,"['Thriller', 'Horror', 'Mystery']","['daughter', 'sadism', 'kidnapping', 'sadistic...",Chris Sivertson,2007-07-27,105,1.5155,https://image.tmdb.org/t/p/w500/7hz8jYHGNsNsnF...,12000000,9620399,There are two sides to every crime.,['https://image.tmdb.org/t/p/w500/7hz8jYHGNsNs...,['KSZ98kUVQFo'],[],"{'id': 5857, 'imdb_id': 'tt0897361', 'wikidata...",R,"[{'name': 'Lindsay Lohan', 'profile_url': 'htt..."
45429,289222,The Zookeeper's Wife,"The account of keepers of the Warsaw Zoo, Jan ...","['Drama', 'History', 'War']","['nazi', 'holocaust (shoah)', 'world war ii', ...",Niki Caro,2017-03-24,126,1.6061,https://image.tmdb.org/t/p/w500/50KGpMiIvSkF4W...,20000000,26152835,They gave all they had to save all they could,['https://image.tmdb.org/t/p/w500/50KGpMiIvSkF...,"['FgIkhuee1uQ', 'ELVMeP5ujtI', 'mREsrNa0Tps', ...","[""**The zoo, the zookeepers and the WWII!**\r\...","{'id': 289222, 'imdb_id': 'tt1730768', 'wikida...",PG-13,"[{'name': 'Jessica Chastain', 'profile_url': '..."
425,117553,Calendar Girl,Three young men go on an end of the summer tri...,"['Comedy', 'Drama']","['california', 'beach', 'tattoo', 'narration',...",John Whitesell,1993-09-03,90,1.3667,https://image.tmdb.org/t/p/w500/ljSqZTl5oophHs...,13000000,2600000,It started with a dream and a stolen convertible.,['https://image.tmdb.org/t/p/w500/ljSqZTl5ooph...,['Ci-QG4w1Tz0'],[],"{'id': 117553, 'imdb_id': 'tt0106505', 'wikida...",PG-13,"[{'name': 'Gabriel Olds', 'profile_url': 'http..."
71239,294284,Debating Robert Lee,A group of jaded high school students sign up ...,['Drama'],"['high school', 'debate', 'high school student...",Dan Polier,2004-09-17,108,0.7952,https://image.tmdb.org/t/p/w500/n7pRyAkF668Gt2...,450000,0,NaN,['https://image.tmdb.org/t/p/w500/xGKi1GyYK4Uq...,[],[],"{'id': 294284, 'imdb_id': 'tt0387973', 'wikida...",R,"[{'name': 'Daniel Letterle', 'profile_url': 'h..."

# Приводим датасет к рабочему виду

In [25]:
df['genres_list'] = df['genres']
df.head(1)

,movie_id,title,overview,genres,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast,genres_list
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['Family', 'Comedy', 'Animation', 'Adventure']","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.554,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/...","['Family', 'Comedy', 'Animation', 'Adventure']"

In [26]:
df['genres'].apply(lambda x: ' '.join(sorted(literal_eval(x)) if isinstance(x, str) else sorted(x)))

0        Adventure Animation Comedy Family
1                 Adventure Family Fantasy
2                           Comedy Romance
3                     Comedy Drama Romance
4                            Comedy Family
                       ...
95496              Horror Mystery Thriller
95497                               Comedy
95498
95499                                Drama
95500
Name: genres, Length: 95501, dtype: str

In [27]:
df['num_genres'] = df['genres'].apply(lambda x: len(x))

In [28]:
df['all_genres'] = df['genres'].apply(lambda x: ' '.join(sorted(literal_eval(x)) if isinstance(x, str) else sorted(x)))

In [29]:
list_of_genres = list(df['genres'].apply(lambda x: ' '.join(sorted(literal_eval(x)) if isinstance(x, str) else sorted(x))))
list_of_genres

['Adventure Animation Comedy Family',
 'Adventure Family Fantasy',
 'Comedy Romance',
 'Comedy Drama Romance',
 'Comedy Family',
 'Action Crime Drama',
 'Comedy Drama Romance',
 'Action Adventure Drama Family',
 'Action Crime Drama Thriller',
 'Action Adventure Thriller',
 'Comedy Drama Romance',
 'Comedy Horror',
 'Adventure Animation Family',
 'Drama History',
 'Action Adventure',
 'Crime Drama',
 'Drama Romance',
 'Comedy',
 'Adventure Comedy Crime',
 'Action Comedy Crime',
 'Comedy Crime Thriller',
 'Crime Mystery Thriller',
 'Action Adventure Crime Thriller',
 'Drama Fantasy',
 'Drama Romance',
 'Drama',
 'Comedy Drama Romance',
 'Drama Romance',
 'Adventure Fantasy Science Fiction',
 'Crime Drama',
 'Drama',
 'Mystery Science Fiction Thriller',
 'Adventure Romance',
 'Comedy Drama Family Fantasy',
 'Drama History Romance',
 'Drama',
 'Adventure Drama Family History',
 'Comedy Family Romance',
 'Comedy Romance',
 'Drama',
 'Drama War',
 'Action Crime Drama Thriller War',
 'Drama Romance',
 'Action Fantasy',
 'Comedy Crime Drama',
 'Drama Romance',
 'Crime Mystery Thriller',
 'Adventure Animation Family Romance',
 'Drama Romance',
 'Crime Drama Thriller',
 'Action Drama Thriller',
 'Comedy Romance',
 'Drama',
 'Comedy Family',
 'Drama',
 'Adventure Comedy Family Fantasy',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Drama Mystery Thriller',
 'Adventure Family Fantasy',
 'Drama Thriller',
 'Drama Music',
 'Comedy Crime',
 'Comedy Romance',
 'Comedy',
 'Action Horror Science Fiction Thriller',
 'Drama Family',
 'Comedy Romance',
 'Comedy Drama',
 'Action Crime Horror Thriller',
 'Action',
 'Comedy Drama Romance',
 'Drama History',
 'Drama Romance',
 'Comedy',
 'Horror Science Fiction War',
 'Documentary',
 'Drama Thriller',
 'Crime Drama Thriller',
 'Drama Family',
 'Crime Drama',
 'Comedy Drama',
 'Drama Romance',
 'Comedy Drama',
 'Drama Romance',
 'Adventure Drama',
 'Adventure Comedy Family',
 'Comedy',
 'Action Crime Thriller',
 'Drama',
 'Drama Horror Thriller',
 'Comedy Fantasy Horror Romance',
 'Comedy Drama Romance',
 'Action Thriller',
 'Comedy',
 'Drama',
 'Action Crime Drama',
 'Documentary',
 'Drama Thriller',
 'Comedy Crime Drama',
 'Comedy Romance',
 'Mystery Science Fiction Thriller',
 'Comedy',
 'Drama Romance',
 'Comedy Drama Family',
 'Adventure Comedy Family',
 'Documentary',
 'Crime',
 'Action Drama History War',
 'Crime Drama',
 'Action Comedy Crime Thriller',
 'Crime Drama Mystery',
 'Drama',
 'Comedy',
 'Documentary',
 'Comedy Crime Drama',
 'Comedy Romance',
 'Comedy Drama',
 'Adventure Comedy Drama',
 'Crime Drama',
 'Comedy Romance',
 'Comedy Drama Romance',
 'Drama Romance',
 'Comedy',
 'Adventure Comedy Family Fantasy',
 'Drama',
 'Documentary',
 'Comedy Romance',
 'Drama',
 'Drama Romance War',
 'Mystery Thriller',
 'Comedy Drama Romance',
 'Documentary Music',
 'Comedy',
 'Documentary',
 'Comedy',
 'Drama',
 'Drama',
 'Drama Romance',
 'Comedy',
 'Drama',
 'Drama',
 'Comedy Drama Romance',
 'Action Comedy Crime Thriller',
 'Adventure Drama Family',
 'Crime Drama',
 'Comedy Drama Romance',
 'Comedy Crime Drama Thriller',
 'Drama History',
 'Action Adventure Drama History War',
 'Drama Horror',
 'Action Crime Fantasy',
 'Drama Romance',
 'Drama Thriller',
 'Comedy',
 'Comedy',
 'Comedy Family Fantasy',
 'Crime Drama Mystery',
 'Action Adventure Science Fiction',
 'Action Drama Thriller War',
 'Documentary',
 'Action Crime Thriller',
 'Crime Mystery Thriller',
 'Action Thriller',
 'Comedy Crime Drama',
 'Crime Drama',
 'Action Adventure Drama Romance',
 'Adventure Comedy Drama Family',
 'Action Crime Drama Thriller',
 'Comedy Drama Romance',
 'Action Adventure Science Fiction',
 'Action Science Fiction',
 'Comedy Drama',
 'Crime Drama',
 'Comedy',
 'Drama Fantasy Horror',
 'Comedy Drama',
 'Drama Romance',
 'Comedy Romance',
 'Action Adventure Fantasy Science Fiction',
 'Comedy Drama Romance',
 'Crime Horror Thriller',
 'Horror Thriller',
 'Action Crime Drama Mystery Thriller',
 'Comedy Romance',
 'Comedy Drama Romance',
 'Action Crime Drama Fantasy Horror Mystery Thriller',
 'Comedy Drama Fantasy',
 'Drama',
 'Drama Romance',
 'Documentary',
 'Drama',
 'Comedy Drama',
 'Comedy Drama',
 'Action Horror Science Fiction',
 'Drama',
 'Crime Drama Science Fiction Thriller',
 'Drama Romance',
 'Crime Thriller',
 'Drama Family Fantasy',
 'Drama Romance',
 'Comedy Drama',
 'Action Thriller',
 'Comedy Drama Family',
 'Documentary',
 'Drama Romance',
 'Action Adventure Science Fiction',
 'Drama',
 'Action Drama History Western',
 'Drama',
 'Action Adventure Comedy Family',
 'Drama',
 'Drama War',
 'Drama Romance',
 'Comedy',
 'Drama Thriller',
 'Comedy Drama',
 'Drama Family',
 'Drama Horror Mystery Thriller',
 'Drama Romance',
 'Comedy',
 'Comedy Drama Romance',
 'Crime Drama Thriller',
 'Fantasy Thriller',
 'Action Crime Thriller',
 'Comedy Crime Fantasy',
 'Drama Thriller',
 'Crime Drama Mystery',
 'Comedy',
 'Comedy Drama Romance',
 'Drama',
 'Comedy Crime Thriller',
 'Comedy Drama History',
 'Comedy Romance',
 'Comedy Drama Romance',
 'Action Adventure Drama Family',
 'Adventure Animation Comedy Family Romance',
 'Drama Horror Thriller',
 'Adventure Drama Family',
 'Drama History Music',
 'Drama Family Fantasy',
 'Adventure Animation Family Fantasy Music',
 'Action Crime Drama Thriller',
 'Documentary',
 'Drama Fantasy',
 'Comedy',
 'Drama Music Romance',
 'Comedy Family',
 'Action Drama Thriller',
 'Comedy Drama Romance',
 'Drama Fantasy Horror',
 'Drama History Romance',
 'Comedy Crime',
 'Comedy Science Fiction',
 'Action Drama Mystery Thriller',
 'Adventure Comedy Family Fantasy',
 'Crime Drama Thriller',
 'Action Adventure Science Fiction',
 'Drama Romance',
 'Drama Family Fantasy',
 'Drama',
 'Drama Thriller',
 'Drama Romance',
 'Action Drama Romance War Western',
 'Adventure Comedy Family',
 'Crime Drama',
 'Crime Drama',
 'Drama Romance',
 'Drama',
 'Comedy Drama History',
 'Drama Horror Romance Science Fiction',
 'Comedy Family',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Drama Family Fantasy',
 'Comedy Romance',
 'Comedy Drama',
 'Crime Drama',
 'Comedy Drama',
 'Drama Thriller',
 'Crime Drama',
 'Action Crime Drama Thriller',
 'Horror',
 'Action Science Fiction Thriller',
 'Drama Romance',
 'Crime Drama Thriller',
 'Comedy Romance',
 'Drama',
 'Action Drama Science Fiction Thriller',
 'Action Crime Drama',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Comedy Crime Thriller',
 'Drama History',
 'Comedy Drama',
 'Drama Romance',
 'Drama History',
 'Drama History',
 'Drama History Romance',
 'Action Drama Romance Thriller Western',
 'Comedy Drama',
 'Comedy',
 'Drama Mystery Romance',
 'Drama',
 'Comedy Drama Mystery',
 'Drama',
 'Comedy Family TV Movie',
 'Drama Horror',
 'Comedy Drama',
 'Adventure Animation Comedy Family Fantasy',
 'Adventure Drama Family Fantasy',
 'Action Thriller',
 'Action Adventure Science Fiction',
 'Comedy Drama Family Fantasy',
 'Crime Drama',
 'Crime Thriller',
 'Drama Thriller',
 'Comedy Drama',
 'Comedy Crime',
 'Comedy Drama Romance',
 'Comedy',
 'Drama Romance War',
 'Action Comedy Fantasy Science Fiction',
 'Comedy Horror Thriller',
 'Action Adventure Science Fiction Thriller',
 'Crime Drama Fantasy Horror Thriller',
 'Drama Romance',
 'Horror Science Fiction Thriller',
 'Comedy',
 'Drama',
 'Crime Drama Thriller',
 'Drama War',
 'Drama Romance',
 'Action Crime Science Fiction Thriller',
 'Comedy Romance',
 'Drama War',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Comedy Drama Family',
 'Comedy Crime Mystery',
 'Comedy Drama',
 'Drama Music',
 'Drama Romance Thriller',
 'Comedy Crime',
 'Action Drama Thriller',
 'Crime Drama Mystery Thriller',
 'Comedy Family Romance',
 'Comedy Drama',
 'Action Fantasy Thriller',
 'Drama',
 'Comedy Family Fantasy',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Crime Drama Thriller',
 'Comedy Drama Romance',
 'Comedy Romance',
 'Comedy Drama Romance',
 'Adventure Drama Family',
 'Documentary',
 'Adventure Animation Drama Family',
 'Drama History',
 'Fantasy Horror Mystery',
 'Comedy Crime Fantasy Romance',
 'Action Adventure Comedy Drama Western',
 'Drama',
 'Comedy Crime',
 'Comedy Drama',
 'Comedy Drama Romance',
 'Crime Drama Thriller',
 'Comedy Family',
 'Drama',
 'Adventure Drama Thriller',
 'Action Thriller',
 'Comedy Romance',
 'Action Crime Science Fiction Thriller',
 'Action Thriller',
 'Drama Romance',
 'Drama Horror Romance',
 'Action Adventure Drama Western',
 'Action Crime Romance Thriller',
 'Comedy Drama',
 'Comedy Drama',
 'Action Comedy Crime',
 'Drama',
 'Drama',
 'Action Comedy Crime Thriller',
 'Crime Drama Romance',
 'Adventure Animation Horror Science Fiction',
 'Action Adventure Comedy Thriller',
 'Action Comedy',
 'Drama Mystery Romance',
 'Action Adventure Crime Drama Thriller',
 'Horror',
 'Documentary',
 'Adventure Crime Drama Romance',
 'Drama Thriller',
 'Action Thriller',
 'Comedy',
 'Comedy Crime Drama',
 'Documentary',
 'Action Adventure Fantasy',
 'Crime Drama',
 'Horror Mystery',
 'Drama Romance Western',
 'Crime Drama Thriller',
 'Comedy Family Fantasy',
 'Comedy Documentary',
 'Drama Romance',
 'Comedy Crime Music',
 'Comedy Family',
 'Action Comedy Crime',
 'Romance Western',
 'Comedy Drama Romance',
 'Comedy Drama Fantasy',
 'Comedy Family',
 'Action Comedy Crime',
 'Adventure Drama Family',
 'Crime Thriller',
 'Action',
 'Drama',
 'Drama Romance',
 'Horror Science Fiction',
 'Drama Romance Thriller',
 'Crime Drama',
 'Adventure Comedy Fantasy Romance',
 'Comedy Drama',
 'Crime Drama Thriller',
 'Comedy Western',
 'Comedy Mystery',
 'Action Adventure Thriller',
 'Comedy Science Fiction',
 'Mystery Romance Thriller',
 'Comedy Crime Thriller',
 'Action Comedy Crime Drama Thriller Western',
 'Drama',
 'Comedy',
 'Comedy Drama',
 'Action Crime Science Fiction',
 'Documentary',
 'Comedy Drama Romance Western',
 'Comedy Crime',
 'Drama',
 'Comedy Romance',
 'Drama',
 'Comedy Music',
 'Comedy Drama',
 'Drama Romance Thriller',
 'Comedy Mystery Romance Thriller',
 'Comedy Romance',
 'Drama Mystery Thriller',
 'Adventure Drama Family',
 'Crime Drama Thriller',
 'Action Drama Thriller',
 'Action Drama History Western',
 'Action Crime Mystery Thriller',
 'Comedy Crime Family',
 'Comedy Drama Romance',
 'Comedy Drama',
 'Drama Thriller',
 'Action Crime Thriller',
 'Drama History War',
 'Action Comedy War',
 'Comedy',
 'Comedy Drama Romance',
 'Drama Romance',
 'Comedy',
 'Comedy Drama Fantasy',
 'Comedy Drama',
 'Comedy',
 'Action Crime Drama Mystery Thriller',
 'Drama',
 'Comedy Drama Romance',
 'Drama History Music',
 'Comedy',
 'Action Crime Thriller',
 'Adventure Science Fiction',
 'Crime Thriller',
 'Action Crime Drama Thriller',
 'Drama History',
 'Adventure Family',
 'Action Adventure Comedy Family Fantasy',
 'Comedy Family',
 'Comedy Western',
 'Drama Romance',
 'Comedy',
 'Thriller',
 'Drama',
 'Comedy Mystery',
 'Crime Drama Thriller',
 'Action Adventure Drama Thriller',
 'Drama Romance',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Drama Romance',
 'Comedy Romance',
 'Comedy Drama Family',
 'Comedy Drama',
 'Action Adventure Drama Family',
 'Comedy Drama',
 'Action Drama Science Fiction Thriller',
 'Adventure Comedy Drama Family Fantasy',
 'Drama Fantasy',
 'Crime Drama Thriller',
 'Drama',
 'Drama Romance',
 'Drama Romance',
 'Action Drama Romance',
 'Horror Science Fiction Thriller',
 'Comedy Crime Drama',
 'Comedy Crime Drama',
 'Drama Romance',
 'Comedy Drama',
 'Action Drama Thriller',
 'Comedy Drama Romance',
 'Action Adventure Crime Science Fiction Thriller',
 'Comedy',
 'Crime Drama Romance',
 'Action Drama Thriller',
 'Drama Romance',
 'Drama History',
 'Drama',
 'Drama',
 'Drama History War',
 'Comedy',
 'Drama',
 'Drama Family',
 'Drama Family Fantasy',
 'Comedy Crime',
 'Action Crime Fantasy',
 'Drama Romance',
 'Comedy Drama',
 'Comedy Drama Family',
 'Comedy Drama',
 'Comedy Drama Mystery',
 'Comedy Drama Romance',
 'Drama Thriller',
 'Drama Science Fiction Thriller',
 'Comedy Drama Romance',
 'Comedy Crime Romance',
 'Action Crime Mystery Thriller',
 'Adventure Comedy Family Fantasy',
 'Action Adventure Crime Drama Thriller',
 'Action',
 'Drama Music',
 'Comedy Drama Romance',
 'Animation Family Fantasy',
 'Action Adventure Comedy Romance',
 'Action Western',
 'Action Drama Thriller',
 'Action Crime Romance',
 'Documentary History',
 'Animation Family Fantasy',
 'Comedy Drama',
 'Drama',
 'Drama Romance Thriller',
 'Comedy Drama',
 'Drama Romance',
 'Comedy Romance',
 'Drama Horror Thriller',
 'Comedy Romance',
 'Comedy Drama',
 'Comedy Drama',
 'Comedy Family',
 'Drama',
 'Comedy Drama Romance TV Movie',
 'Drama Romance',
 'Comedy',
 'Comedy Drama',
 'Comedy Family Romance',
 'Comedy',
 'Adventure Comedy Family',
 'Crime Drama Thriller',
 'Comedy Drama History Mystery',
 'Documentary History',
 'Comedy Romance',
 'Comedy Drama',
 'Drama Romance',
 'Comedy Family Romance',
 'Comedy Family',
 'Drama Fantasy Mystery Romance Thriller',
 'Adventure Animation Family Fantasy Romance',
 'Action Science Fiction Thriller',
 'Adventure Drama Western',
 'Action Drama Thriller',
 'Action Crime Fantasy',
 'Crime Drama Thriller',
 'Animation Family Fantasy',
 'Animation Family Fantasy Romance',
 'Animation Family Fantasy',
 'Comedy Romance',
 'Comedy Drama Fantasy',
 'Western',
 'Crime Thriller',
 'Drama Romance',
 'Documentary History Music',
 'Comedy Romance',
 'Comedy Romance',
 'Horror Thriller',
 'Drama Romance',
 'Crime Drama Thriller',
 'Adventure Comedy Drama Family',
 'Adventure Animation Fantasy Music Science Fiction',
 'Horror Science Fiction Thriller',
 'Comedy Romance',
 'Drama Romance',
 'Drama Mystery Thriller',
 'Comedy Drama',
 'Adventure Animation Comedy Family',
 'Drama Romance',
 'Comedy Romance',
 'Comedy Family',
 'Adventure Drama',
 'Drama',
 'Comedy Drama Romance',
 'Comedy Drama',
 'Comedy Crime Romance Thriller',
 'Comedy Crime Drama Thriller',
 'Crime Drama Mystery Thriller',
 'Crime Drama',
 'Drama Romance',
 'Adventure Animation Family Fantasy Romance',
 'Drama History War',
 'Comedy',
 'Comedy Family Fantasy Science Fiction',
 'Comedy Drama',
 'Crime Drama Horror Thriller',
 'Comedy',
 'Comedy Drama Romance',
 'Comedy Drama',
 'Horror Mystery Thriller',
 'Adventure Comedy Drama Family',
 'Drama Romance',
 'Comedy',
 'Comedy',
 'Drama Romance',
 'Drama Mystery Thriller War',
 'Action Adventure Thriller',
 'Comedy Drama',
 'Drama Romance',
 'Comedy',
 'Horror Mystery Thriller',
 'Action Adventure Drama Fantasy',
 'Drama',
 'Drama History',
 'Action Comedy',
 'Comedy',
 'Music',
 'Crime Drama Thriller',
 'Comedy Drama Romance',
 'Adventure Animation Family Fantasy',
 'Thriller',
 'Comedy',
 'Comedy Crime Drama',
 'Comedy Drama War',
 'Drama Romance War',
 'Action Thriller',
 'Drama History',
 'Drama',
 'Comedy Science Fiction',
 'Drama',
 'Animation Comedy Family Science Fiction',
 'Action Adventure Comedy Fantasy Science Fiction',
 'Action Drama Thriller',
 'Comedy Horror Science Fiction',
 'Drama Thriller',
 'Drama Romance',
 'Drama Mystery Science Fiction',
 'Comedy Crime Drama',
 'Documentary',
 'Documentary',
 'Drama Horror Thriller',
 'Drama',
 'Drama Romance',
 'Action Adventure Comedy Family',
 'Drama Romance',
 'Drama Romance',
 'Action Adventure Science Fiction Thriller',
 'Drama',
 'Action Crime Drama Thriller',
 'Crime Mystery Thriller',
 'Crime Drama Romance Thriller',
 'Comedy Crime Drama Romance Thriller',
 'Drama Romance',
 'Comedy Romance',
 'Comedy Drama Family Romance',
 'Drama History',
 'Drama',
 'Drama Mystery Romance',
 'Action Adventure Drama',
 'Comedy Drama Music Romance',
 'Drama',
 'Crime Drama Mystery Thriller',
 'Comedy Romance',
 'Animation Comedy Family',
 'Comedy',
 'Adventure Family',
 'Drama Mystery Romance Thriller',
 'Drama',
 'Drama Fantasy Western',
 'Adventure Drama History Romance',
 'Action Crime Drama',
 'Comedy',
 'Comedy Fantasy',
 'Comedy Fantasy Romance Science Fiction',
 'Animation Comedy Family',
 'Documentary',
 'Drama TV Movie',
 'Drama Fantasy Horror',
 'Comedy',
 'Crime Drama',
 'Documentary',
 'Comedy Romance',
 'Drama',
 'Drama Mystery Thriller',
 'Action Crime Drama Thriller',
 'Action Adventure Thriller',
 'Comedy',
 'Comedy Horror',
 'Action Adventure Drama',
 'Action Adventure Science Fiction',
 'Drama',
 'Comedy',
 'Action Animation Science Fiction',
 'Fantasy Horror',
 'Action Comedy',
 'Comedy Drama',
 'Animation Comedy Family',
 'Crime Drama',
 'Comedy Family',
 'Horror Science Fiction Thriller',
 'Action Comedy Drama War',
 'Comedy War',
 'Comedy Drama Fantasy',
 'Comedy Documentary',
 'Comedy Drama Romance',
 'Adventure Drama Family Mystery',
 'Adventure Drama Family',
 'Documentary',
 'Action Drama',
 '',
 'Documentary',
 'Drama History War',
 'Action Adventure',
 'Comedy Crime Drama',
 'Comedy Drama',
 'Drama Romance',
 'Comedy Drama Family',
 'Drama',
 'Comedy Drama Family',
 'Drama',
 'Documentary',
 'Music Romance',
 'Comedy',
 'Drama Romance',
 'Drama',
 'Drama Horror Mystery',
 'Comedy Drama Romance',
 'Drama History War Western',
 'Crime Drama',
 'Comedy Romance',
 'Action Adventure Science Fiction',
 'Drama Romance',
 'Action Drama Thriller',
 'Animation Drama Family',
 'Comedy Drama Thriller',
 'Comedy',
 'Action Mystery Thriller',
 'Documentary',
 'Comedy Fantasy Romance Science Fiction',
 'Drama History Romance',
 'Drama Romance War',
 'Fantasy',
 'Drama',
 'Crime Drama',
 'Comedy Drama',
 'Drama Romance',
 'Comedy Crime Drama',
 'Action Adventure Thriller',
 'Comedy Horror',
 'Drama Mystery Romance',
 'Comedy Drama Family',
 'Drama Fantasy Romance Science Fiction',
 'Comedy Drama Romance',
 'Comedy Romance',
 'Crime Drama Thriller',
 'Crime Drama',
 'Comedy Drama Romance',
 'Adventure Drama Family',
 'Action',
 'Comedy Family Fantasy',
 'Drama Fantasy',
 'Comedy Family',
 'Crime Drama Romance',
 'Action Mystery Thriller',
 'Drama War',
 'Comedy Family',
 'Comedy',
 'Adventure Drama',
 'Mystery Romance Thriller',
 'Drama War',
 'Drama Romance',
 'Drama',
 'Comedy',
 'Drama',
 'Drama Mystery',
 'Adventure Drama Family Fantasy',
 'Comedy Fantasy',
 'Comedy',
 'Comedy Drama History Romance',
 'Action Thriller',
 'Comedy Crime Romance',
 'Comedy Drama',
 'Action Drama Thriller',
 'Action Science Fiction Thriller',
 'Comedy Family Fantasy',
 'Comedy Drama Romance',
 'Action Fantasy Thriller',
 'Comedy Family',
 'Drama Horror Thriller',
 'Comedy Horror',
 'Drama',
 'Drama Romance',
 'Crime Drama Mystery',
 'Drama Romance',
 'Drama',
 'Comedy Drama',
 'Action Adventure Science Fiction Thriller',
 'Crime Drama',
 'Drama History',
 'Comedy Drama Romance',
 'Drama Music',
 'Drama',
 'Drama',
 'Comedy',
 'Drama',
 'Crime Drama',
 'Drama History Music',
 'Comedy Drama',
 'Action Crime Thriller',
 'Comedy Drama',
 'Drama',
 'Drama',
 'Crime Drama Thriller',
 'Comedy Family',
 'Comedy Crime Drama Thriller',
 'Crime Drama',
 'Comedy',
 'Comedy Fantasy Romance',
 'Drama',
 'Drama',
 'Drama',
 'Action Crime Drama',
 'Action Comedy Crime Thriller',
 'Comedy Drama',
 'Drama',
 'Horror Mystery Science Fiction Thriller',
 'Horror Science Fiction',
 'Comedy Family',
 'Drama Thriller',
 'Drama',
 'Comedy Family Fantasy',
 'Action Comedy Crime',
 'Drama Romance War',
 'Drama Romance',
 'Crime Mystery Romance Thriller',
 'Horror Thriller',
 'Comedy Drama Romance',
 'Drama History',
 'Drama Romance',
 'Drama Romance',
 'Drama Romance',
 'Adventure Drama History Romance War',
 'Comedy Romance',
 'Comedy Romance',
 'Comedy Music Romance',
 'Comedy Music Romance',
 'Comedy Drama Romance',
 'Mystery Romance Thriller',
 'Mystery Thriller',
 'Comedy Romance',
 'Crime Drama Mystery Thriller',
 'Comedy Romance',
 'Adventure Thriller',
 'Comedy Drama Romance',
 'Comedy Crime Romance',
 'Comedy Mystery Romance',
 'Drama Romance',
 'Crime Mystery Thriller',
 'Comedy Music Romance',
 'Comedy Drama Romance',
 'Comedy Drama Romance',
 'Comedy Drama Family',
 'Comedy Drama Family Romance',
 'Adventure Family Fantasy',
 'Drama Romance War',
 'Comedy Drama',
 'Drama',

In [30]:
Counter(' '.join(list_of_genres).split()).most_common()

[('Drama', 40816),
 ('Comedy', 28187),
 ('Thriller', 14871),
 ('Romance', 13667),
 ('Documentary', 11756),
 ('Action', 11380),
 ('Horror', 10805),
 ('Crime', 9720),
 ('Adventure', 6756),
 ('Family', 5916),
 ('Science', 5762),
 ('Fiction', 5762),
 ('Mystery', 5670),
 ('TV', 5399),
 ('Movie', 5399),
 ('Fantasy', 5391),
 ('Animation', 5310),
 ('Music', 4378),
 ('History', 3708),
 ('War', 2744),
 ('Western', 1980)]

In [31]:
top_genres = [m[0] for m in Counter(' '.join(list_of_genres).split()).most_common(15)]
df = df.drop(['genres'], axis=1)

In [32]:
for g in top_genres:
    df['genre_' + g] = df['all_genres'].apply(lambda x: 1 if g in x else 0)

In [33]:
df.sample(8)

,movie_id,title,overview,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast,genres_list,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie
32830,102155,Hitler,Richard Basehart stars as one of the most infl...,"['nazi', 'world war ii', 'biography']",Stuart Heisler,1962-03-21,107,2.2438,https://image.tmdb.org/t/p/w500/NDK54o9AKgSot7...,0,0,The private life of Hitler revealed for the fi...,['https://image.tmdb.org/t/p/w500/NDK54o9AKgSo...,['j5iAwe4Lfnw'],[],"{'id': 102155, 'imdb_id': 'tt0056072', 'wikida...",NaN,"[{'name': 'Richard Basehart', 'profile_url': '...","['History', 'War']",18,History War,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18792,288290,Mon Paradis - Der Winterpalast,A portrait of five St. Petersburgians and thei...,"['museum', 'woman director']",Elfi Mikesch,2001-01-01,48,0.2568,NaN,0,0,NaN,[],[],[],"{'id': 288290, 'imdb_id': 'tt0393493', 'wikida...",NaN,[],['Documentary'],15,Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
10974,51601,San Quentin,Ex-Army officer Jameson takes a job a prison g...,['san quentin'],Lloyd Bacon,1937-05-24,70,4.3058,https://image.tmdb.org/t/p/w500/vXVOti9ouBpscf...,0,0,... Amazing Drama of Desperate Men Behind the ...,['https://image.tmdb.org/t/p/w500/vXVOti9ouBps...,['Bo5JAba5fOI'],[],"{'id': 51601, 'imdb_id': 'tt0029511', 'wikidat...",NaN,"[{'name': ""Pat O'Brien"", 'profile_url': 'https...","['Action', 'Drama']",19,Action Drama,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
38480,287179,The Iron Ministry,"Filmed over three years on China’s railways, T...",['ministry'],J.P. Sniadecki,2014-08-15,82,0.9021,https://image.tmdb.org/t/p/w500/9wlqe0sqskGfFj...,0,0,NaN,['https://image.tmdb.org/t/p/w500/9wlqe0sqskGf...,['mjtTYgXuoWs'],[],"{'id': 287179, 'imdb_id': 'tt3907314', 'wikida...",NaN,[],['Documentary'],15,Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
42450,95008,The House That Vanished,"A young model, Valerie, and her petty thief bo...","['murder', 'model', 'incest']",José Ramón Larraz,1973-12-07,103,0.4034,https://image.tmdb.org/t/p/w500/34LrQxQMDUboPH...,0,0,"If You Have Ever Lived Alone, You Will Never F...",['https://image.tmdb.org/t/p/w500/34LrQxQMDUbo...,['GOzWeO9zeZY'],['**_Gritty psychological English horror from ...,"{'id': 95008, 'imdb_id': 'tt0070655', 'wikidat...",R,"[{'name': 'Andrea Allan', 'profile_url': 'http...","['Horror', 'Mystery']",21,Horror Mystery,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
91510,1531601,My Little Grandma,"When her daughter abandons the family, a devot...",[],Khương Ngọc,2025-10-17,119,6.4332,https://image.tmdb.org/t/p/w500/jv2bu10yEL3UgB...,0,0,NaN,['https://image.tmdb.org/t/p/w500/jv2bu10yEL3U...,['YPCtgD0KnGk'],[],"{'id': 1531601, 'imdb_id': None, 'wikidata_id'...",NaN,"[{'name': 'Hồng Đào', 'profile_url': 'https://...","['Family', 'Drama']",19,Drama Family,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
72420,639562,Sunburned,Feeling neglected by her mother and sister on ...,[],Carolina Hellsgård,2019-10-18,92,1.3518,https://image.tmdb.org/t/p/w500/yMJC5rNSW6gZbL...,0,0,NaN,['https://image.tmdb.org/t/p/w500/4in0C1E7byGO...,[],[],"{'id': 639562, 'imdb_id': 'tt10295834', 'wikid...",NaN,"[{'name': 'Sabine Timoteo', 'profile_url': 'ht...",['Drama'],9,Drama,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
60185,54985,Wings of Life,A beautiful love story in danger. Our future d...,"['nature', 'bee', 'pollination', 'hummingbird'...",Louie Schwartzberg,2011-03-16,77,0.2896,https://image.tmdb.org/t/p/w500/bIbAl2rFaQ7WjI...,0,0,A Love Story that Feeds the Earth,['https://image.tmdb.org/t/p/w500/dkxewDQPpjnC...,['J6r8BNnEDRk'],[],"{'id': 54985, 'imdb_id': 'tt1222816', 'wikidat...",NaN,"[{'name': 'Meryl Streep', 'profile_url': 'http...",['Documentary'],15,Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [34]:
df['keywords'].apply(lambda x: ' '.join(sorted(literal_eval(x)) if isinstance(x, str) else sorted(x)))

0        anthropomorphism boy next door buddy bullying ...
1        based on young adult novel board game disappea...
2        best friend duringcreditsstinger fishing itali...
3        adoring african american friendship african am...
4        aging baby confidence contraception daughter g...
                               ...
95496
95497
95498
95499
95500
Name: keywords, Length: 95501, dtype: str

In [35]:
list_of_keywords = []
for keywords in df['keywords']:
    if isinstance(keywords, str):
        parsed = ast.literal_eval(keywords)
        list_of_keywords.append(sorted(parsed))
    else:
        list_of_keywords.append(sorted(keywords))
list_of_keywords

[['anthropomorphism',
  'boy next door',
  'buddy',
  'bullying',
  'computer animation',
  'elementary school',
  'friends',
  'friendship',
  'jealousy',
  'mission',
  'neighborhood',
  'new toy',
  'pixar',
  'rescue',
  'resourcefulness',
  'rivalry',
  'toy',
  'toy car',
  'toy comes to life',
  'villain',
  'walkie talkie'],
 ['based on young adult novel',
  'board game',
  'disappearance',
  'giant insect',
  'jungle',
  'recluse',
  'stampede',
  'vibrant'],
 ['best friend',
  'duringcreditsstinger',
  'fishing',
  'italian restaurant',
  'old friends',
  'old man',
  'pranks',
  'sequel',
  'wedding'],
 ['adoring',
  'african american friendship',
  'african american romance',
  'anxious',
  'based on novel or book',
  'cautionary',
  'celebratory',
  'comforting',
  'divorce',
  'friendship between women',
  'single mother'],
 ['aging',
  'baby',
  'confidence',
  'contraception',
  'daughter',
  'gynecologist',
  'los angeles, california',
  'midlife crisis',
  'parent child relationship',
  'pregnancy',
  'pregnant',
  'pregnant woman',
  'remake',
  'sequel'],
 ['antagonistic',
  'assertive',
  'authoritarian',
  'bank job',
  'bank robbery',
  'betrayal',
  'bold',
  'cat and mouse',
  'chase',
  'crime epic',
  'criminal mastermind',
  'cynical',
  'detective',
  'ex-con',
  'gang',
  'heist',
  'honor',
  'loner',
  'los angeles, california',
  'murder',
  'neo-noir',
  'obsession',
  'one last job',
  'robbery',
  'thief'],
 ['birthday party',
  'brother brother relationship',
  'chauffeur',
  'family business ',
  'family disapproval',
  'father daughter relationship',
  'high society',
  'impossible love',
  'long island, new york',
  'marriage engagement',
  'merger',
  'millionaire',
  'paris, france',
  'playboy',
  'romantic',
  'scheme',
  'sibling relationship',
  'teenage crush',
  'transformation',
  'unlikely romance',
  'wealth differences',
  'wealthy family'],
 ['based on novel or book',
  'male friendship',
  'mississippi river',
  'restless youth',
  'rural americana'],
 ['explosive',
  'hostage',
  'ice hockey',
  'pittsburgh penguins',
  'pittsburgh, pennsylvania',
  'terrorism',
  'vice president'],
 ['computer virus',
  'cossack',
  'cuba',
  'electromagnetic pulse',
  'falsely accused',
  'kgb',
  'red army',
  'satellite',
  'secret base',
  'secret identity',
  'secret intelligence service',
  'special car',
  'st. petersburg, russia',
  'time bomb'],
 ['class differences',
  'lobbyist',
  'new love',
  'romantic',
  'the white house',
  'usa president',
  'widower',
  'wildlife conservation'],
 ['dracula', 'satire', 'spoof', 'vampire'],
 ['alaska',
  'bear attack',
  'cartoon',
  'cartoon animal',
  'cartoon wolf',
  'dog',
  'dog sled',
  'dog-sledding race',
  'goose',
  'pet',
  'pets',
  'villain',
  'wolf'],
 ['1960s',
  '1970s',
  'ambiguous',
  'biography',
  'disapproving',
  'disdainful',
  'disheartening',
  'earnest',
  'empathetic',
  'frustrated',
  'government',
  'historical figure',
  'presidential election',
  'richard nixon',
  'usa president',
  'washington dc, usa',
  'watergate scandal'],
 ['17th century',
  'adventurer',
  'betrayal',
  'exotic island',
  'heroine',
  'island',
  'map',
  'pirate',
  'pirate ship',
  'scalp',
  'ship',
  'swashbuckler',
  'sword fight',
  'treasure',
  'treasure map'],
 ['1970s',
  '1980s',
  'based on novel or book',
  'brutal violence',
  'car bomb',
  'casino',
  'cocaine',
  'desert',
  'dramatic',
  'drug abuse',
  'fbi',
  'fbi surveillance',
  'gambling',
  'greed',
  'italian american',
  'jewish american',
  'las vegas',
  'mafia',
  'marriage',
  'money',
  'murder',
  'organized crime',
  'overdose',
  'pimp',
  'poker',
  'rise and fall',
  'safe deposit box'],
 ['1800s',
  '19th century',
  'based on novel or book',
  'bloodletting',
  'country life',
  'countryside',
  'decorum',
  'devonshire, england',
  'dowry',
  'free spirited',
  'horse carriage',
  'inheritance',
  'london, england',
  'marry for money',
  'military officer',
  'penniless',
  'period drama',
  'pneumonia',
  'rainstorm',
  'secret engagement',
  'secret love',
  'servant',
  'sisters love',
  'social class',
  'social elite',
  'sussex',
  'widow',
  'young love'],
 ['anthology',
  'bet',
  'hoodlum',
  'hotel',
  'hotel room',
  'los angeles, california',
  'multiple storylines',
  "new year's eve",
  'sperm',
  'witch',
  'woman director'],
 ['africa',
  'animals',
  'bat',
  'human animal relationship',
  'indigenous',
  'kidnapping',
  'pets',
  'slapstick comedy',
  'stupidity'],
 ['new york city',
  'new york subway',
  'sibling relationship',
  'subway',
  'train robbery'],
 ['based on novel or book',
  'business',
  'con',
  'debt',
  'drugs',
  'gambling',
  'gangster',
  'hollywood',
  'mafia',
  'miami, florida',
  'mobster',
  'money',
  'murder',
  'producer',
  'travel'],
 ['cowardliness',
  'police brutality',
  'police operation',
  'police protection',
  'psychologist',
  'psychology',
  'serial killer'],
 ['bank',
  'caribbean sea',
  'cat',
  'central intelligence agency (cia)',
  'detroit, michigan',
  'double cross',
  'hidden camera',
  'hitman',
  'mexican standoff',
  'mission of murder',
  'police chase',
  'rescue',
  'rivalry',
  'seattle, washington',
  'shootout',
  'silencer',
  'sniper rifle'],
 ['albino',
  'christ allegory',
  'extrasensory perception',
  'fainting',
  'flickering light',
  'healing power',
  'held at gunpoint',
  'pale',
  'psionic power',
  'teacher student relationship',
  'teenage boy'],
 ['alcohol',
  'alcohol abuse',
  'alcoholism',
  'casino',
  'depressing',
  'dramatic',
  'dying and death',
  'hotel room',
  'individual',
  'las vegas',
  'los angeles, california',
  'love at first sight',
  'lovesickness',
  'movie business',
  'prostitute',
  'rage and hate',
  'screenwriter',
  'tragic',
  'unsociability'],
 ['based on play or musical',
  'friends',
  'jealousy',
  'shakespeare',
  'the moors (people)'],
 ['1970s',
  'coming of age',
  'female friendship',
  'gynecologist',
  'photocopier',
  'truth or dare',
  'woman director'],
 ['admiral', 'based on novel or book', 'napoleonic wars', 'old flame'],
 ['aging',
  'child kidnapping',
  'childhood',
  'clone',
  'dreams',
  'dystopia',
  'eye',
  'flea',
  'friendship',
  'island',
  'rescue',
  'steampunk'],
 ['1930s',
  'cabaret singer',
  'chinese mafia',
  'chinese triad',
  'coming of age',
  'criminal underworld',
  'drug lord',
  'mistress',
  'modern china',
  'nightclub singer',
  'shanghai, china',
  'triad'],
 ['amusement park',
  'based on memoir or autobiography',
  'california',
  'high school',
  'karate',
  'naval officer',
  'rap music',
  'schoolteacher',
  'teacher'],
 ['1990s',
  '2030s',
  'absurd',
  'airplane',
  'alternate history',
  'animal research',
  'anxious',
  'asylum',
  'biological weapon',
  "child's point of view",
  'cockroach',
  'complicated',
  'critical',
  'disease',
  'dormitory',
  'drug use',
  'dystopia',
  'epidemic',
  'escaped animal',
  'falling down stairs',
  'flashback',
  'florida keys',
  'future noir',
  'gas mask',
  'insane asylum',
  'insanity',
  'inspirational',
  'intense',
  'irreverent',
  'jail',
  'lethal virus',
  'lion',
  'medical research',
  'melancholy',
  'mental breakdown',
  'mental institution',
  'monkey',
  'mysterious',
  'nonlinear timeline',
  'ominous',
  'pantyhose',
  'paradox',
  'paranoia',
  'past',
  'philadelphia, pennsylvania',
  'pimp',
  'post-apocalyptic future',
  'preposterous',
  'prison cell',
  'psychiatric hospital',
  'psychiatrist',
  'psychosis',
  'recurring dream',
  'reflective',
  'remake',
  'schizophrenia',
  'stockholm syndrome',
  'street life',
  'subterranean',
  'suspenseful',
  'time travel',
  'tooth',
  'trapped',
  'underground',
  'virus',
  'volunteer',
  'world war i'],
 [],
 ['affection',
  'alarm clock',
  'animals',
  'anthropomorphism',
  "based on children's book",
  'cat',
  'christmas',
  'dog',
  'duck',
  'farm',
  'farmer',
  'grandson',
  'heroism',
  'pig',
  'piglet',
  'separation',
  'sheep',
  'sheepdog',
  'talking pig'],
 ['conscientious objector', 'england', 'painter', 'polyamory', 'soldier'],
 ['angry',
  'bitter',
  'callous',
  'charity',
  'court',
  'court case',
  'cowardliness',
  'death penalty',
  'death row',
  'death sentence',
  'depressing',
  'despair',
  'doomed man',
  'dreary',
  'forgiveness',
  'horrified',
  'incredulous',
  'lethal injection',
  'mercy petition',
  'nun',
  'penalty',
  'prison',
  'prison cell',
  'rage and hate',
  'rape',
  'right and justice',
  'self-discovery',
  'sentence',
  'socially deprived family',
  'therapist',
  'unsociability'],
 [],
 ['identical twin', 'matchmaking', 'orphan', 'relationship sabotage'],
 ['based on novel or book',
  'coming of age',
  'conflict',
  'gay theme',
  'high school',
  'high school friends',
  'make a match',
  'makeover',
  'match making',
  'matchmaker',
  'matchmaking',
  'popular girl',
  'puberty',
  'spoiled child',
  'wedding',
  'woman director'],
 ['1940s',
  'apartheid',
  'based on novel or book',
  'priest',
  'race relations',
  'south africa'],
 ['england', 'kidnapping', 'king', 'murder'],
 ['1960s',
  'armored truck',
  'bronx, new york city',
  'drug abuse',
  'heist',
  'loss of virginity',
  'medic',
  'mercy killing',
  'money',
  'post-traumatic stress disorder (ptsd)',
  'redemption',
  'revolutinoary',
  'vietnam',
  'war veteran'],
 ['17th century',
  'british monarchy',
  'court',
  'fountain',
  'gloves',
  'jealousy',
  'medicine',
  'spaniel',
  'wealth'],
 ['action hero',
  'alternate dimension',
  'based on video game',
  'ghost',
  'god',
  'good versus evil',
  'gore',
  'hand to hand combat',
  'island',
  'magic',
  'martial arts',
  'monster',
  'mortal kombat',
  'ninja',
  'saving the world',
  'sorcerer',
  'supernatural power',
  'tournament',
  'underground fighting',
  'villain',
  'warrior'],
 ['adultery',
  'based on novel or book',
  'mockumentary',
  'narcissistic personality disorder',
  'new hampshire',
  'obsession',
  'satirical',
  'winter'],
 ['advice',
  'extramarital affair',
  'family holiday',
  'grandmother',
  'love',
  'marriage',
  'marriage proposal',
  'married couple',
  'monogamy',
  'quilt',
  'wedding vows',
  'woman director'],
 ['anxious',
  'awestruck',
  'corpse',
  'depravity',
  'depressing',
  'detective',
  'disdainful',
  'insomnia',
  'intense',
  'investigation',
  'murder',
  'neo-noir',
  'police',
  'psychopath',
  'rage and hate',
  'religion',
  's.w.a.t.',
  'sadism',
  'self-fulfilling prophecy',
  'serial killer',
  'seven deadly sins',
  'seven: los siete pecados capitales',
  'shocking',
  'shootout',
  'suspenseful',
  'urban gothic'],
 ['17th century',
  'animal sidekick',
  'based on myths, legends or folklore',
  'cartoon',
  'colonisation',
  'colony',
  'culture clash',
  'forbidden love',
  'gold rush',
  'intercultural relationship',
  'musical',
  'native american',
  'princess',
  'shamanism',
  'star crossed lovers',
  'villain',
  'virginia'],
 ['lesbian', 'lgbt', 'professor', 'woman director'],
 ['affectation',
  'cargo ship',
  'criminal',
  'criminal mastermind',
  'flashback',
  'heist',
  'incredulous',
  'los angeles, california',
  'mind game',
  'mystery villain',
  'neo-noir',
  'new york city',
  'police corruption',
  'rashomon effect',
  'relatives',
  'robbery',
  'shocking',
  'theft',
  'whodunit'],
 ['boat chase',
  'bodyguard',
  'corrupt cop',
  'counterfeit money',
  'female bodyguard',
  'female martial artist',
  'female police officer',
  'helicopter',
  'horse polo',
  'jetski',
  'martial arts',
  'mental hospital',
  'murder of a police officer',
  'police officer',
  'police officer killed',
  'police surveillance',
  'shooting a police officer',
  'speedboat chase'],
 ['adoption',
  'adoptive father',
  'adoptive mother',
  'childlessness',
  'illegal prostitution',
  'kids',
  'looking for  birth parents',
  'prostitute'],
 [],
 ['football (soccer)', 'sports', 'woman director'],
 ['alcohol',
  'artist',
  'drugs',
  'folk singer',
  'heroin',
  'seattle, washington',
  'sibling relationship',
  'singer',
  'sister sister relationship'],
 ['excalibur', 'king arthur', 'sword'],
 ['baltimore, usa',
  'christmas',
  'family clan',
  'family conflict',
  'generations conflict',
  'thanksgiving',
  'woman director'],
 ['fisherman',
  'island',
  'letter',
  'love',
  'naples, italy',
  'poet',
  'postman',
  'poverty'],
 [],
 ["based on children's book",
  'based on novel or book',
  'cupboard',
  'game',
  'parallel world',
  'puppet',
  'toy comes to life',
  'toy soldier'],
 ['grieving parents', 'gun', 'rape', 'rape and revenge', 'self-defense'],
 ['1960s',
  '1990s',
  'composer',
  'deaf-mute',
  'disabled',
  'father son relationship',
  'forced retirement',
  'high school',
  'high school teacher',
  'husband wife relationship',
  'inspiring teacher',
  'marching band',
  'mentor',
  'music teacher',
  'portland, oregon',
  'retirement party',
  'sign languages',
  'teacher student relationship',
  'teaching'],
 ['cousin',
  'date',
  'gang',
  'gangster',
  'hip-hop',
  'hood',
  'parody',
  'racism',
  'satirical',
  'slang',
  'social satire'],
 ['1990s',
  'art theft',
  'art thief',
  'boston, massachusetts',
  'car thief',
  'criminals',
  'fbi agent',
  'island',
  'mansion',
  'new england',
  'painting',
  'rhode island',
  'romcom',
  'seasickness',
  'squatting',
  'stealing a car',
  'stolen car',
  'thief'],
 ['biosphere', 'biotope', 'pollution', 'vegetarian'],
 ['based on short story',
  'computer',
  'cyberpunk',
  'cyberspace',
  'hacker',
  'revenge',
  'scientist',
  'supernatural power',
  'surveillance',
  'sword fight',
  'technology',
  'virtual reality',
  'world domination'],
 [],
 ['estate agent',
  'love triangle',
  'menage a trois',
  'polyamory',
  'southern france',
  'van',
  'woman director'],
 ['bully',
  'drug dealer',
  'drugs',
  'los angeles, california',
  'male friendship',
  'marijuana',
  'parent child relationship',
  'pot smoking',
  'rap music',
  'rapper',
  'slacker',
  'urban life'],
 ['bank robber',
  'bank robbery',
  'barefoot',
  'boa constrictor',
  'crucifix',
  'dancing',
  'female stripping',
  'foot fetish',
  'holy water',
  'hostage situation',
  'killer on the run',
  'loss of faith',
  'mexican american border',
  'preacher',
  'priest',
  'recreational vehicle',
  'sheriff',
  'showdown',
  'sibling relationship',
  'siege',
  'stripper',
  'vampire',
  'witty'],
 ['based on novel or book',
  'bomb',
  'car crash',
  'chase',
  'conspiracy',
  'damsel in distress',
  'detective',
  'double cross',
  'fbi',
  'foot chase',
  'fugitive',
  'grenade launcher',
  'gunfight',
  'hacker',
  'handcuffs',
  'held at gunpoint',
  'hostage',
  'kgb',
  'kidnapping',
  'machine gun',
  'miami, florida',
  'on the run',
  'parking garage',
  'pizza',
  'police detective',
  'police protection',
  'police station',
  'psychopath',
  'remake',
  'rogue agent',
  'sadism',
  'sadist',
  'shootout',
  'spy',
  'woman lawyer'],
 ['campus',
  'college',
  'friendship',
  'graduate',
  'male friendship',
  'video store'],
 ['boxer', 'lawyer', 'nun', 'paris, france'],
 ['family relationships', 'florist'],
 ['bully'],
 ['alien planet', 'android horror', 'man vs machine', 'struggle for survival'],
 [],
 ['hit-and-run', 'loss of loved one', 'revenge', 'tragedy'],
 ['blackmail',
  'blasphemy',
  'court case',
  'courtroom',
  'courtroom drama',
  'jurors',
  'legal thriller',
  'son',
  'trial'],
 ['celebration', 'fish', 'goldfish', 'money'],
 ['boat',
  'bounty hunter',
  'coffin',
  'denver, colorado',
  'diner',
  'extramarital affair',
  'friendship',
  'gangster',
  'godmother',
  'hitman',
  'illegal prostitution',
  'mafia',
  'murder',
  'paranoia',
  'parent child relationship',
  'psychopath',
  'revenge',
  'way of life'],
 ['domestic violence',
  'family history',
  'feminism',
  'free love',
  'freedom',
  'indian summer ',
  'loss of loved one',
  'male homosexuality',
  'mathematics',
  'mentally disabled',
  'parent child relationship',
  'peasant',
  'philosophy',
  'rape',
  'right and justice',
  'single',
  'suicide',
  'underdog',
  'university',
  'village',
  'village life',
  'widow',
  'woman director',
  'world war ii'],
 ['family relationships', 'racial segregation', 'rural area'],
 ['acting lesson',
  'actor',
  'brother sister relationship',
  'family dynamics',
  'family home',
  'hamptons',
  'matriarch',
  'method acting',
  'playwright',
  'theater community',
  'theater director',
  'theater play',
  'theater troupe',
  'theatre group'],
 ['based on short story',
  'brother sister incest',
  'brother sister sex',
  'class society',
  'incest',
  'insect',
  'naturalist',
  'rich woman poor man',
  'scientist',
  'unfaithful wife',
  'victorian england'],
 ['1960s',
  'caribbean sea',
  'coming of age',
  'diary',
  'discipline',
  'gay interest',
  'male bonding',
  'sail',
  'sailing',
  'sailing trip',
  'seasickness',
  'squall',
  'storm at sea',
  'survival',
  'teenage boy'],
 ['bali',
  'boss',
  'brother brother relationship',
  'bully',
  'employer employee relationship',
  'father son relationship',
  'fistfight',
  'hotel manager',
  'jewel theft',
  'mischief',
  'orangutan',
  'single father'],
 ['candid camera',
  'corrupt politician',
  'double act',
  'nitrous oxide',
  'political satire',
  'woman director'],
 ['assassination', 'los angeles, california', 'politics'],
 [],
 ['19th century',
  'housemaid',
  'jekyll and hyde',
  'laboratory',
  'monster',
  'servant'],
 ['african american comedy',
  'african american romance',
  'black vampire',
  'brooklyn, new york city',
  'vampire'],
 ['coming of age',
  'friendship',
  'group of friends',
  'hometown',
  'massachusetts',
  'small town'],
 ['abandoned mine',
  'action hero',
  'antagonistic',
  'audacious',
  'authoritarian',
  'betrayal',
  'boxing',
  'canyon',
  'countdown',
  'desert',
  'explosion',
  'fistfight',
  'gunfight',
  'helicopter',
  'hostile',
  'humvee',
  'major',
  'mexican standoff',
  'military',
  'nuclear device',
  'ominous',
  'park ranger',
  'pilot',
  'river',
  'stealth aircraft',
  'train',
  'underground'],
 ['black and white',
  'christmas',
  'gay theme',
  'hamlet',
  'nostalgic',
  'theater',
  'theatre group',
  'transvestite'],
 ['aggressive',
  'black and white',
  'breakdance',
  'day in a life',
  'ethnic diversity',
  'ghetto',
  'gun death',
  'hip-hop',
  'housing project',
  'male friendship',
  'paris suburb',
  'paris, france',
  'police brutality',
  'police shooting',
  'racism',
  'rebellious youth',
  'riot police',
  'skinheads',
  'socially deprived family',
  'street riots',
  'urban violence',
  'xenophobia'],
 ['criminal',
  'england',
  'future',
  'money',
  'nihilism',
  'prison',
  'rivalry',
  'shopping mall',
  'spray paint',
  'stealing',
  'vandalism'],
 ['based on true story',
  'hollywood',
  'narration',
  'prostitution',
  'sex crime'],
 ['accidental shooting',
  'city hall',
  'corrupt judge',
  'corrupt mayor',
  'corrupt police officials',
  'corruption',
  'drug dealer',
  'investigation',
  'mafia',
  'mafia family',
  'mayor',
  'mob hit',
  'new york city',
  'police',
  'political ambition',
  'political corruption',
  'presidential election',
  'suicide by gun',
  'undercover',
  'undercover agent',
  'war on drugs'],
 ['absurd',
  'based on short film',
  'burglar',
  'escapade',
  'heist',
  'joyous',
  'language barrier',
  'laundry room',
  'maid',
  'motel',
  'nervous breakdown',
  'psychiatric hospital',
  'robbery',
  'sibling relationship',
  'theft'],
 [],
 ['crime scene',
  'dangerous side effects',
  'death of wife',
  'experimental drug',
  'medical examiner',
  'murder',
  'murdered wife',
  'neurobiology',
  'obsession',
  'painful memories',
  'search for truth',
  'seattle, washington',
  'suspicion of murder'],
 ['anger issues',

In [36]:
top_keywords = [m[0] for m in Counter([i for j in list_of_keywords for i in j]).most_common(30)]

In [37]:
df['num_keywords'] = df['keywords'].apply(lambda x: len(x))
df['all_keywords'] = df['keywords'].apply(lambda x: ' '.join(sorted(literal_eval(x)) if isinstance(x, str) else sorted(x))) 
for g in top_keywords:
    df['keyword_' + g] = df['all_keywords'].apply(lambda x: 1 if g in x else 0)

In [38]:
df.head(3)

,movie_id,title,overview,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast,genres_list,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.5540,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/...","['Family', 'Comedy', 'Animation', 'Adventure']",46,Adventure Animation Comedy Family,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,292,anthropomorphism boy next door buddy bullying ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"['giant insect', 'board game', 'disappearance'...",Joe Johnston,1995-12-15,104,2.5713,https://image.tmdb.org/t/p/w500/iWV47r6kFneCiA...,65000000,262821940,It's a jungle in here.,['https://image.tmdb.org/t/p/w500/nLXYV4WmYUF4...,"['aPkVamOQzVQ', 'BBu-chLYTJ8', '1xKR759ghEw', ...","[""Throw the dice and take a turn, Jumanji made...","{'id': 8844, 'imdb_id': 'tt0113497', 'wikidata...",PG,"[{'name': 'Robin Williams', 'profile_url': 'ht...","['Adventure', 'Fantasy', 'Family']",34,Adventure Family Fantasy,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,121,based on young adult novel board game disappea...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"['fishing', 'sequel', 'old man', 'best friend'...",Howard Deutch,1995-12-22,101,2.5156,https://image.tmdb.org/t/p/w500/1FSXpj5e8l4KH6...,25000000,71500000,Still Yelling. Still Fighting. Still Ready for...,['https://image.tmdb.org/t/p/w500/1FSXpj5e8l4K...,['rEnOoWs3FuA'],[],"{'id': 15602, 'imdb_id': 'tt0113228', 'wikidat...",PG-13,"[{'name': 'Walter Matthau', 'profile_url': 'ht...","['Romance', 'Comedy']",21,Comedy Romance,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,129,best friend duringcreditsstinger fishing itali...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [39]:
# number of casted persons
df['cast'].apply(lambda x: len(x) if x != {} else 0).value_counts()

cast
2       3554
109      418
108      332
107      322
110      295
        ...
122        1
182        1
6328       1
6795       1
76         1
Name: count, Length: 7193, dtype: int64

In [40]:
df['external_ids'][0]

"{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_id': 'Q171048', 'facebook_id': None, 'instagram_id': 'toystory', 'twitter_id': 'toystory'}"

In [41]:
def get_names(x):
    if pd.isna(x):
        return []
    if isinstance(x, str):
        x = ast.literal_eval(x)  
    if isinstance(x, list):
        return [p.get('name') for p in x if isinstance(p, dict) and p.get('name')]
    return []

In [154]:
cast_names = df['cast'].apply(get_names)
cast_names

KeyError: 'cast'

In [43]:
Counter(cast_names.explode().dropna()).most_common(15)

[('Bess Flowers', 502),
 ('Mel Blanc', 300),
 ('Sam Harris', 251),
 ('Eric Roberts', 245),
 ('Frank Welker', 243),
 ("William H. O'Brien", 222),
 ('Harold Miller', 220),
 ('Christopher Lee', 201),
 ('Danny Trejo', 187),
 ('Bert Stevens', 187),
 ('Lee Phelps', 185),
 ('Kenner G. Kemp', 182),
 ('Irving Bacon', 182),
 ('Franklyn Farnum', 180),
 ('Byron Foulger', 180)]

In [44]:
df['cast_num'] = df['cast'].apply(lambda x: len(x) if x != {} else 0)
top_cast_name = list(Counter(cast_names.explode().dropna()).most_common(15))
for g in top_cast_name:
    df['cast_name_' + g[0]] = df['cast'].apply(lambda x: 1 if g[0] in str(x) else 0)

In [45]:
df.head()

,movie_id,title,overview,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast,genres_list,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical,cast_num,cast_name_Bess Flowers,cast_name_Mel Blanc,cast_name_Sam Harris,cast_name_Eric Roberts,cast_name_Frank Welker,cast_name_William H. O'Brien,cast_name_Harold Miller,cast_name_Christopher Lee,cast_name_Danny Trejo,cast_name_Bert Stevens,cast_name_Lee Phelps,cast_name_Kenner G. Kemp,cast_name_Irving Bacon,cast_name_Franklyn Farnum,cast_name_Byron Foulger
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.5540,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/...","['Family', 'Comedy', 'Animation', 'Adventure']",46,Adventure Animation Comedy Family,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,292,anthropomorphism boy next door buddy bullying ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3402,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"['giant insect', 'board game', 'disappearance'...",Joe Johnston,1995-12-15,104,2.5713,https://image.tmdb.org/t/p/w500/iWV47r6kFneCiA...,65000000,262821940,It's a jungle in here.,['https://image.tmdb.org/t/p/w500/nLXYV4WmYUF4...,"['aPkVamOQzVQ', 'BBu-chLYTJ8', '1xKR759ghEw', ...","[""Throw the dice and take a turn, Jumanji made...","{'id': 8844, 'imdb_id': 'tt0113497', 'wikidata...",PG,"[{'name': 'Robin Williams', 'profile_url': 'ht...","['Adventure', 'Fantasy', 'Family']",34,Adventure Family Fantasy,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,121,based on young adult novel board game disappea...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2684,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"['fishing', 'sequel', 'old man', 'best friend'...",Howard Deutch,1995-12-22,101,2.5156,https://image.tmdb.org/t/p/w500/1FSXpj5e8l4KH6...,25000000,71500000,Still Yelling. Still Fighting. Still Ready for...,['https://image.tmdb.org/t/p/w500/1FSXpj5e8l4K...,['rEnOoWs3FuA'],[],"{'id': 15602, 'imdb_id': 'tt0113228', 'wikidat...",PG-13,"[{'name': 'Walter Matthau', 'profile_url': 'ht...","['Romance', 'Comedy']",21,Comedy Romance,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,129,best friend duringcreditsstinger fishing itali...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1466,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","['based on novel or book', 'single mother', 'd...",Forest Whitaker,1995-12-22,127,3.4707,https://image.tmdb.org/t/p/w500/qJU6rfil5xLVb5...,16000000,81452156,Friends are the people who let you be yourself...,['https://image.tmdb.org/t/p/w500/afLVNPUxvBZ5...,['j9xml1CxgXI'],[],"{'id': 31357, 'imdb_id': 'tt0114885', 'wikidat...",R,"[{'name': 'Whitney Houston', 'profile_url': 'h...","['Comedy', 'Drama', 'Romance']",30,Comedy Drama Romance,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,206,adoring african american friendship african am...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3868,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"['daughter', 'baby', 'parent child relationshi...",Charles Shyer,1995-12-08,106,2.9373,https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGrpB...,0,76594107,Just when his world is back to normal... he's ...,['https://image.tmdb.org/t/p/w500/rj4LBtwQ0uGr...,['yCg8WNQwe0A'],[],"{'id': 11862, 'imdb_id': 'tt0113041', 'wikidat...",PG,"[{'name': 'Steve Martin', 'profile_url': 'http...","['Comedy', 'Family']",20,Comedy Family,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,213,aging baby confidence contraception daughter g...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,4498,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [51]:
top_directors = Counter(df['director'].dropna()).most_common(15)
for g in top_directors:
    df['director_name_' + g[0]] = df['director'].apply(lambda x: 1 if g[0] in str(x) else 0)

In [53]:
df.to_csv('../tmp/pre_one_hot_data.csv', index=False)

In [55]:
df.head(1)

,movie_id,title,overview,keywords,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,cast,genres_list,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical,cast_num,cast_name_Bess Flowers,cast_name_Mel Blanc,cast_name_Sam Harris,cast_name_Eric Roberts,cast_name_Frank Welker,cast_name_William H. O'Brien,cast_name_Harold Miller,cast_name_Christopher Lee,cast_name_Danny Trejo,cast_name_Bert Stevens,cast_name_Lee Phelps,cast_name_Kenner G. Kemp,cast_name_Irving Bacon,cast_name_Franklyn Farnum,cast_name_Byron Foulger,director_name_Georges Méliès,director_name_Chuck Jones,director_name_Friz Freleng,director_name_Tex Avery,director_name_Michael Curtiz,director_name_John Ford,director_name_David DeCoteau,director_name_Richard Thorpe,director_name_Werner Herzog,director_name_Jean-Luc Godard,director_name_Charlie Chaplin,director_name_Jack Hannah,director_name_Alfred Hitchcock,director_name_Gordon Douglas,director_name_William Beaudine
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","['rescue', 'friendship', 'mission', 'jealousy'...",John Lasseter,1995-11-22,81,18.554,https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5...,30000000,394436586,The adventure takes off when toys come to life!,['https://image.tmdb.org/t/p/w500/uXDfjJbdP4ij...,"['_hIfuYVgBrY', 'TZOCUtoygtc', 'CxwTLktovTU', ...","[""This movie came out when I was three. Now I'...","{'id': 862, 'imdb_id': 'tt0114709', 'wikidata_...",G,"[{'name': 'Tom Hanks', 'profile_url': 'https:/...","['Family', 'Comedy', 'Animation', 'Adventure']",46,Adventure Animation Comedy Family,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,292,anthropomorphism boy next door buddy bullying ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3402,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [57]:
df.drop(['keywords', 'cast', 'genres_list'],axis=1, inplace=True)

In [113]:
df.sample()

,movie_id,title,overview,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical,cast_num,cast_name_Bess Flowers,cast_name_Mel Blanc,cast_name_Sam Harris,cast_name_Eric Roberts,cast_name_Frank Welker,cast_name_William H. O'Brien,cast_name_Harold Miller,cast_name_Christopher Lee,cast_name_Danny Trejo,cast_name_Bert Stevens,cast_name_Lee Phelps,cast_name_Kenner G. Kemp,cast_name_Irving Bacon,cast_name_Franklyn Farnum,cast_name_Byron Foulger,director_name_Georges Méliès,director_name_Chuck Jones,director_name_Friz Freleng,director_name_Tex Avery,director_name_Michael Curtiz,director_name_John Ford,director_name_David DeCoteau,director_name_Richard Thorpe,director_name_Werner Herzog,director_name_Jean-Luc Godard,director_name_Charlie Chaplin,director_name_Jack Hannah,director_name_Alfred Hitchcock,director_name_Gordon Douglas,director_name_William Beaudine,len_overview
81894,724495,The Woman King,"The story of the Agojie, the all-female unit o...",Gina Prince-Bythewood,2022-09-16,135,6.8576,https://image.tmdb.org/t/p/w500/438QXt1E3WJWb3...,50000000,97300000,Her reign begins.,['https://image.tmdb.org/t/p/w500/438QXt1E3WJW...,"['nt1Ixu2JzZU', 'OKZZbVM9SSk', 'eiQAn6hMKQ8', ...","[""The Woman King is a touching film that balan...","{'id': 724495, 'imdb_id': 'tt8093700', 'wikida...",PG-13,30,Action Drama History,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,352,19th century admiring africa aggressive arrang...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3787,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,336

In [60]:
df['overview']

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
95496    What seems like a demon is in fact something c...
95497    The film tells of a penniless young man who is...
95498    Lust follows desire as sure as night follows d...
95499    Octavio and Adela were born on the same day, A...
95500    Documentary celebrating 50 years of The Good L...
Name: overview, Length: 95501, dtype: str

In [62]:
df['len_overview'] = df['overview'].apply(lambda x: len(x) if isinstance(x, str) else 0)

In [116]:
df['len_tagline'] = df['tagline'].apply(lambda x: len(x) if isinstance(x, str) else 0)

In [71]:
df['popularity'].value_counts(ascending=True)

popularity
18.5540      1
10.5781      1
5.1194       1
3.7544       1
3.9348       1
          ...
0.0000      96
0.0286     109
0.0071     145
0.0214     148
0.0143     242
Name: count, Length: 39349, dtype: int64

In [120]:
certification_list = ['R''NR','PG-13','PG','G','NC-17','PG-13','TVMA']

In [121]:
df['have_certification'] = df['certification'].apply(lambda x: 1 if x in certification_list else 0)

In [122]:
df_cert = df['certification']

In [124]:
type(df_cert)

pandas.Series

In [125]:
df_one = pd.get_dummies(data=df_cert, dtype=int)

In [126]:
df_one

       G  NC-17  NR  PG  PG-13  PG-13   R  TVMA
0      1      0   0   0      0       0  0     0
1      0      0   0   1      0       0  0     0
2      0      0   0   0      1       0  0     0
3      0      0   0   0      0       0  1     0
4      0      0   0   1      0       0  0     0
...   ..    ...  ..  ..    ...     ... ..   ...
95496  0      0   0   0      0       0  0     0
95497  0      0   0   0      0       0  0     0
95498  0      0   0   0      0       0  0     0
95499  0      0   0   0      0       0  0     0
95500  0      0   0   0      0       0  0     0

[95501 rows x 8 columns]

In [127]:
df_fin = pd.concat([df, df_one], axis=1)

In [129]:
df_fin.sample()

,movie_id,title,overview,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical,cast_num,cast_name_Bess Flowers,cast_name_Mel Blanc,cast_name_Sam Harris,cast_name_Eric Roberts,cast_name_Frank Welker,cast_name_William H. O'Brien,cast_name_Harold Miller,cast_name_Christopher Lee,cast_name_Danny Trejo,cast_name_Bert Stevens,cast_name_Lee Phelps,cast_name_Kenner G. Kemp,cast_name_Irving Bacon,cast_name_Franklyn Farnum,cast_name_Byron Foulger,director_name_Georges Méliès,director_name_Chuck Jones,director_name_Friz Freleng,director_name_Tex Avery,director_name_Michael Curtiz,director_name_John Ford,director_name_David DeCoteau,director_name_Richard Thorpe,director_name_Werner Herzog,director_name_Jean-Luc Godard,director_name_Charlie Chaplin,director_name_Jack Hannah,director_name_Alfred Hitchcock,director_name_Gordon Douglas,director_name_William Beaudine,len_overview,len_tagline,have_certification,G,NC-17,NR,PG,PG-13,PG-13,R,TVMA
36100,317442,The Last: Naruto the Movie,Two years after the events of the Fourth Great...,Tsuneo Kobayashi,2014-12-06,114,5.0083,https://image.tmdb.org/t/p/w500/bAQ8O5Uw6Fedtl...,750000,19840000,NaN,['https://image.tmdb.org/t/p/w500/bAQ8O5Uw6Fed...,"['SDIvvapG0sE', 'tA3yE4_t6SY', 'mksl3tYdyK4', ...",[],"{'id': 317442, 'imdb_id': 'tt3717532', 'wikida...",PG-13,34,Action Animation Romance,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,63,anime martial artist martial arts ninja shounen,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1857,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,546,0,1,0,0,0,0,1,0,0,0

In [145]:
df[df['popularity'] == 0]

,movie_id,title,overview,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,certification,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical,cast_num,cast_name_Bess Flowers,cast_name_Mel Blanc,cast_name_Sam Harris,cast_name_Eric Roberts,cast_name_Frank Welker,cast_name_William H. O'Brien,cast_name_Harold Miller,cast_name_Christopher Lee,cast_name_Danny Trejo,cast_name_Bert Stevens,cast_name_Lee Phelps,cast_name_Kenner G. Kemp,cast_name_Irving Bacon,cast_name_Franklyn Farnum,cast_name_Byron Foulger,director_name_Georges Méliès,director_name_Chuck Jones,director_name_Friz Freleng,director_name_Tex Avery,director_name_Michael Curtiz,director_name_John Ford,director_name_David DeCoteau,director_name_Richard Thorpe,director_name_Werner Herzog,director_name_Jean-Luc Godard,director_name_Charlie Chaplin,director_name_Jack Hannah,director_name_Alfred Hitchcock,director_name_Gordon Douglas,director_name_William Beaudine,len_overview,len_tagline,have_certification,G,NC-17,NR,PG,PG-13,PG-13,R,TVMA
5406,146231,Hybrid,The life story of Milford Beeghly: Iowa farmer...,Monteith McCollum,2000-11-24,92,0.0,https://image.tmdb.org/t/p/w500/kABfKZwOPXANrr...,0,0,NaN,['https://image.tmdb.org/t/p/w500/kABfKZwOPXAN...,[],[],"{'id': 146231, 'imdb_id': 'tt0267563', 'wikida...",NaN,15,Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,114,0,0,0,0,0,0,0,0,0,0
15132,227196,Freedom Park,Returning to their hometown in desperate need ...,NaN,2004-09-10,99,0.0,NaN,275000,0,Where little league bats hit big time gambling,[],[],[],"{'id': 227196, 'imdb_id': 'tt0386474', 'wikida...",NaN,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,413,46,0,0,0,0,0,0,0,0,0
15345,507149,Zero Degrees of Separation,This feature documentary breaks with the sensa...,Elle Flanders,2005-06-22,85,0.0,https://image.tmdb.org/t/p/w500/iTKXuH8JeHD26K...,0,0,NaN,['https://image.tmdb.org/t/p/w500/iTKXuH8JeHD2...,[],[],"{'id': 507149, 'imdb_id': 'tt0454990', 'wikida...",NaN,15,Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,690,0,0,0,0,0,0,0,0,0,0
18383,5422,Erotic Nights of the Living Dead,A sailor takes an American businessman and his...,Joe D'Amato,1980-11-06,111,0.0,https://image.tmdb.org/t/p/w500/a3zkPRXAg848c6...,0,0,NaN,['https://image.tmdb.org/t/p/w500/dNXWrowvBuv9...,['yNrdpCiYFLY'],[],"{'id': 5422, 'imdb_id': 'tt0079642', 'wikidata...",NR,10,Horror,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,89,adultery island legend mindbreak sailing three...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,530,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,293,0,0,0,0,1,0,0,0,0,0
19615,60152,L.A. Zombie,"An extraterrestrial zombie, whose appearance c...",Bruce LaBruce,2010-01-10,103,0.0,https://image.tmdb.org/t/p/w500/kSyz0OX1CLRFqu...,0,0,He CAME to fuck the DEAD back to LIFE,['https://image.tmdb.org/t/p/w500/kSyz0OX1CLRF...,['DWSyay-zz6Q'],[],"{'id': 60152, 'imdb_id': 'tt1594921', 'wikidat...",NC-17,10,Horror,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,40,gay pornography gay theme lgbt,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1364,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,210,37,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83417,869804,Tugging Diary,Tugging Diary documents a footbridge over a ye...,Yan Wai Yin,2020-12-17,16,0.0,https://image.tmdb.org/t/p/w500/wzIAtRpTgRySbb...,0,0,NaN,['https://image.tmdb.org/t/p/w500/wzIAtRpTgRyS...,['yu1SE1M_9Qc'],[],"{'id': 869804, 'imdb_id': 'tt21221096', 'wikid...",NaN,28,Animation Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,101,avant-garde footbridge graffiti hong kong prot...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,553,0,0,0,0,0,0,0,0,0,0
84653,1103214,The Doll,"Ayoub is a rather old man , decides to re-marr...",Asghar Yousefinejad,2023-03-01,90,0.0,https://image.tmdb.org/t/p/w500/tOBhgj8bxKjK8O...,0,0,NaN,['https://image.tmdb.org/t/p/w500/tOBhgj8bxKjK...,[],[],"{'id': 1103214, 'imdb_id': 'tt27261231', 'wiki...",NaN,9,Drama,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,573,0,0,0,0,0,0,0,0,0,0
85200,1073459,Mongoloid,A documentary film exploring the manner in whi...,Bruce Conner,1978-01-01,4,0.0,https://image.tmdb.org/t/p/w500/jpnWFD9Dk0ptLn...,0,0,NaN,['https://image.tmdb.org/t/p/w500/jpnWFD9Dk0pt...,[],[],"{'id': 1073459, 'imdb_id': 'tt0130871', 'wikid...",NaN,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,344,0,0,0,0,0,0,0,0,0,0
85531,580535,Rattler,"After accidentally killing a woman's dog, Rust...",NaN,NaN,14,0.0,NaN,0,0,NaN,[],[],[],"{'id': 580535, 'imdb_id': 'tt0306001', 'wikida...",NaN,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,115,0,0,0,0,0,0,0,0,0,0
86254,1048470,Mountain Flesh,"In a Swiss mountain village, hikers head out, ...",Valentina Shasivari,2022-11-09,18,0.0,https://image.tmdb.org/t/p/w500/aU4jayV8YxFt6r...,0,0,NaN,['https://image.tmdb.org/t/p/w500/aU4jayV8YxFt...,[],[],"{'id': 1048470, 'imdb_id': 'tt27201962', 'wiki...",NaN,15,Documentary,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,250,0,0,0,0,0,0,0,0,0,0

In [147]:
df['year'] = df['release_date'].apply(lambda x: x.split('-')[0] if isinstance(x, str) else 0)
df['month'] = df['release_date'].apply(lambda x: x.split('-')[1] if isinstance(x, str) else 0)
df['day'] = df['release_date'].apply(lambda x: x.split('-')[2] if isinstance(x, str) else 0)

In [ ]:
df.drop('certification', axis=1, inplace=True)

In [152]:
df.sample(3)

,movie_id,title,overview,director,release_date,runtime,popularity,poster_url,budget,revenue,tagline,poster_urls,video_keys,review_texts,external_ids,num_genres,all_genres,genre_Drama,genre_Comedy,genre_Thriller,genre_Romance,genre_Documentary,genre_Action,genre_Horror,genre_Crime,genre_Adventure,genre_Family,genre_Science,genre_Fiction,genre_Mystery,genre_TV,genre_Movie,num_keywords,all_keywords,keyword_woman director,keyword_based on novel or book,keyword_murder,keyword_short film,keyword_biography,keyword_lgbt,keyword_based on true story,keyword_gay theme,keyword_musical,keyword_revenge,keyword_christmas,keyword_new york city,keyword_sequel,keyword_love,keyword_world war ii,keyword_sports,keyword_coming of age,keyword_black and white,keyword_friendship,keyword_silent film,keyword_martial arts,keyword_family,keyword_serial killer,keyword_police,keyword_anime,keyword_remake,keyword_high school,keyword_kidnapping,keyword_parent child relationship,keyword_based on play or musical,cast_num,cast_name_Bess Flowers,cast_name_Mel Blanc,cast_name_Sam Harris,cast_name_Eric Roberts,cast_name_Frank Welker,cast_name_William H. O'Brien,cast_name_Harold Miller,cast_name_Christopher Lee,cast_name_Danny Trejo,cast_name_Bert Stevens,cast_name_Lee Phelps,cast_name_Kenner G. Kemp,cast_name_Irving Bacon,cast_name_Franklyn Farnum,cast_name_Byron Foulger,director_name_Georges Méliès,director_name_Chuck Jones,director_name_Friz Freleng,director_name_Tex Avery,director_name_Michael Curtiz,director_name_John Ford,director_name_David DeCoteau,director_name_Richard Thorpe,director_name_Werner Herzog,director_name_Jean-Luc Godard,director_name_Charlie Chaplin,director_name_Jack Hannah,director_name_Alfred Hitchcock,director_name_Gordon Douglas,director_name_William Beaudine,len_overview,len_tagline,have_certification,G,NC-17,NR,PG,PG-13,PG-13,R,TVMA,year,month,day
20752,61663,Why Not Me?,Four gay French expatriots share a business in...,Stéphane Giusti,1998-11-18,94,1.5512,https://image.tmdb.org/t/p/w500/gFnhRI9RWcyEG2...,0,0,Don't tell my parents about my sex life; I'll ...,['https://image.tmdb.org/t/p/w500/gFnhRI9RWcyE...,['sOCfX2JfbjA'],"['""no but... since i was little, i was always ...","{'id': 61663, 'imdb_id': 'tt0162556', 'wikidat...",21,Comedy Romance,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,21,gay theme lgbt,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2072,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,160,55,0,0,0,0,0,0,0,0,0,1998,11,18
39281,297063,Svens Geheimnis,Sven is a twelve year old pocket-picker and wo...,Roland Suso Richter,1995-09-26,89,1.1330,NaN,0,0,NaN,[],[],[],"{'id': 297063, 'imdb_id': 'tt0111329', 'wikida...",21,Drama TV Movie,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,34,high school gang pickpocket,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1293,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,258,0,0,0,0,0,0,0,0,0,0,1995,09,26
72881,381617,Mirror People,To a sound-track of fun-house screams and cack...,Kathy Rose,1974-01-01,5,0.0143,https://image.tmdb.org/t/p/w500/i4C21GjwD8qdor...,0,0,NaN,['https://image.tmdb.org/t/p/w500/i4C21GjwD8qd...,[],[],"{'id': 381617, 'imdb_id': 'tt7595848', 'wikida...",13,Animation,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,340,0,0,0,0,0,0,0,0,0,0,1974,01,01

In [153]:
drop_features = ['movie_id', 'release_date', 'director', 'poster_url', 'poster_urls', 'video_keys', 'external_ids', 'title']
cat_features = ['overview', 'all_genres', 'tagline', 'review_texts', 'all_keywords']
num_features = ['runtime', 'popularity', 'budget', 'revenue' , 'num_genres', 'cast_num', 'len_overview', 'len_tagline', 'year', 'month', 'day']
sparse_features = [x for x in df.columns if (x not in drop_features) and (x not in cat_features) and (x not in num_features)]